// Parses one issue page of the Rakia weekly newsletter site (rakia-weekly.vercel.app) into the
// `content` shape newsletter_issues stores (see NewsletterContent in wall-ops.ts). The site is
// static HTML generated by rakia's build_site.py, so a few anchored regexes are enough and no
// HTML parser dependency is needed. Images on the site are inline data URIs, too big to keep in
// the feed: they come back separately in `images`, and the importer stores them as files (see
// newsletter-images.ts) and fills in each item's `image` URL.
//
// Pure: no network and no database, so it can be tested against saved pages.

export const NEWSLETTER_SITE = 'https://rakia-weekly.vercel.app';

export type ParsedNews = { cat: string; il?: boolean; date: string; src: string; title: string; dek: string; url: string; image: string | null };
/** An inline picture from the page: its MIME type and base64 bytes. */
export type InlineImage = { mime: string; base64: string };
/** date: as the wall shows it ("27–29.10"); end: its last day as YYYY-MM-DD, so the feed can drop it once it has passed. */
export type ParsedTicker = { kind: 'אירוע' | 'הזדמנות'; date: string; name: string; end: string };
export type ParsedIssue = {
  issue_date: string;
  source_url: string;
  content: { issue: { range: string; url: string }; summary: string[]; featured: number[]; news: ParsedNews[]; ticker: ParsedTicker[] };
  /** One entry per news item, same order: the inline picture to store, or null (none, or already a URL in `image`). */
  images: (InlineImage | null)[];
  /** The Israeli Space Forum's own events that have not ended yet; they also go into the directorate's events. */
  forum: ForumEvent[];
};
/** start/end: YYYY-MM-DD (the same day for a one-day event); times HH:MM in Israel time when the page gives them. */
export type ForumEvent = { title: string; place: string; description: string; url: string; start: string; end: string; startTime?: string; endTime?: string };

const MONTHS: Record<string, number> = {
  ינואר: 1, פברואר: 2, מרץ: 3, מרס: 3, אפריל: 4, מאי: 5, יוני: 6, יולי: 7, אוגוסט: 8, ספטמבר: 9, אוקטובר: 10, נובמבר: 11, דצמבר: 12,
};
const MAX_TICKER = 14;

const ENTITIES: Record<string, string> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' };
function decode(s: string): string {
  return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e: string) => {
    if (e[0] === '#') return String.fromCodePoint(e[1].toLowerCase() === 'x' ? parseInt(e.slice(2), 16) : Number(e.slice(1)));
    return ENTITIES[e.toLowerCase()] ?? m;
  });
}
/** Inner HTML → plain text on one line. */
function text(html: string | undefined): string {
  return decode((html || '').replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]+>/g, '')).replace(/[‎‏]/g, '').replace(/\s+/g, ' ').trim();
}
function first(re: RegExp, s: string): string | undefined { return re.exec(s)?.[1]; }
function attr(tag: string, name: string): string { return decode(first(new RegExp(`${name}="([^"]*)"`), tag) || ''); }

/** The HTML of one <section id="…">, up to the next section. */
function section(html: string, id: string): string {
  const start = html.search(new RegExp(`<section[^>]*\\bid="${id}"`));
  if (start < 0) return '';
  const end = html.indexOf('</section>', start);
  return html.slice(start, end < 0 ? undefined : end);
}
/** Each element `<tag class="cls …">…</tag>` (non-nested tags only: a, article). */
function blocks(html: string, tag: string, cls: string): { open: string; body: string }[] {
  const re = new RegExp(`(<${tag}\\s[^>]*class="${cls}[\\s"][^>]*>)([\\s\\S]*?)</${tag}>`, 'g');
  return [...html.matchAll(re)].map(m => ({ open: m[1], body: m[2] }));
}

/** "27 בספטמבר עד 3 באוקטובר 2026" → "27.9–3.10"; "23–29 באוגוסט" → "23–29.8". Unparseable text is kept as is. */
export function compactRange(raw: string): string {
  const s = raw.replace(/\s+/g, ' ').trim();
  const m = /(\d{1,2})(?:\s+ב([א-ת]+))?\s*(?:עד|–|-)\s*(\d{1,2})\s+ב([א-ת]+)/.exec(s);
  if (!m) return s;
  const m2 = MONTHS[m[4]], m1 = m[2] ? MONTHS[m[2]] : m2;
  if (!m1 || !m2) return s;
  return m1 === m2 ? `${Number(m[1])}–${Number(m[3])}.${m2}` : `${Number(m[1])}.${m1}–${Number(m[3])}.${m2}`;
}

/**
 * The last calendar day a short date text refers to, as YYYY-MM-DD, or null.
 * Accepts "13.12", "27–29.10", "11–14.1.2027"; the year is inferred near `refIso`.
 */
export function endDate(s: string, refIso: string): string | null {
  const all = [...s.matchAll(/(\d{1,2})\.(\d{1,2})(?:\.(\d{4}))?/g)];
  const m = all[all.length - 1];
  if (!m) return null;
  const d = Number(m[1]), mo = Number(m[2]);
  if (d < 1 || d > 31 || mo < 1 || mo > 12) return null;
  let y = m[3] ? Number(m[3]) : Number(refIso.slice(0, 4));
  const refMonth = Number(refIso.slice(5, 7));
  if (!m[3] && mo < refMonth - 6) y += 1;                          // "11.1" in an October issue is next year
  if (!m[3] && mo > refMonth + 6) y -= 1;
  return `${y}-${String(mo).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
}
/** The short date as the wall shows it: "13.12", "27–29.10" (a trailing year is dropped). */
function shortWhen(s: string): string {
  const m = /(\d{1,2}(?:[–-]\d{1,2})?\.\d{1,2})(?:\.\d{4})?/.exec(s);
  return m ? m[1].replace('-', '–') : '';
}

/** Splits "28.09 · SpaceX / Payload" into date and source. */
function dateAndSource(srcHtml: string): { date: string; src: string } {
  const t = text(srcHtml);
  const i = t.indexOf(' · ');
  return i < 0 ? { date: '', src: t } : { date: t.slice(0, i).trim(), src: t.slice(i + 3).trim() };
}

/** The background image of a .lead-img / .card-img element: an http(s) URL, or inline bytes. */
function picture(html: string, cls: string): { url: string | null; inline: InlineImage | null } {
  const src = first(new RegExp(`class="${cls}"[^>]*?background-image:url\\(['"]?([^'")]+)`), html) || '';
  const data = /^data:(image\/[a-z+.-]+);base64,([A-Za-z0-9+/=\s]+)$/i.exec(src);
  if (data) return { url: null, inline: { mime: data[1].toLowerCase(), base64: data[2].replace(/\s+/g, '') } };
  return { url: /^https?:\/\//.test(src) ? decode(src) : null, inline: null };
}

function parseNews(html: string): { news: ParsedNews[]; images: (InlineImage | null)[] } {
  const sec = section(html, 'news');
  const out: ParsedNews[] = [];
  const pics: (InlineImage | null)[] = [];

  // The lead story: a .lead-card with its scope chip (ישראל / בינ״ל) and a category chip.
  const leadStart = sec.indexOf('class="lead-card');
  if (leadStart >= 0) {
    const leadEnd = sec.search(/class="(filters|news-grid)/);
    const lead = sec.slice(leadStart, leadEnd > leadStart ? leadEnd : undefined);
    const title = text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, lead));
    if (title) {
      const { date, src } = dateAndSource(first(/<span class="src">([\s\S]*?)<\/span>\s*<\/div>/, lead) || '');
      const pic = picture(lead, 'lead-img');
      pics.push(pic.inline);
      out.push({
        cat: text(first(/class="chip-line[^"]*">([\s\S]*?)<\/span>/, lead)),
        il: text(first(/class="chip-inv[^"]*">([\s\S]*?)<\/span>/, lead)) === 'ישראל' || undefined,
        date, src, title,
        dek: text(first(/<p(?![^>]*more-p)[^>]*>([\s\S]*?)<\/p>/, lead)),
        url: attr(first(/(<a\s[^>]*href="[^"]*")/, lead) || '', 'href'),
        image: pic.url,
      });
    }
  }

  for (const { open, body } of blocks(sec, 'article', 'card')) {
    const title = text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, body));
    if (!title) continue;
    const { date, src } = dateAndSource(first(/<span class="src">([\s\S]*?)<\/span>\s*<\/div>/, body) || '');
    const pic = picture(body, 'card-img');
    pics.push(pic.inline);
    out.push({
      cat: attr(open, 'data-cat'),
      il: attr(open, 'data-scope') === 'il' || undefined,
      date, src, title,
      dek: text(first(/<p class="teaser">([\s\S]*?)<\/p>/, body)),
      url: attr(first(/(<a\s[^>]*href="[^"]*")/, body) || '', 'href'),
      image: pic.url,
    });
  }
  const keep = out.map((n, i) => (n.cat ? i : -1)).filter(i => i >= 0);
  return { news: keep.map(i => out[i]), images: keep.map(i => pics[i]) };
}

function parseTicker(html: string, issueDate: string, today: string): ParsedTicker[] {
  const items: ParsedTicker[] = [];
  const add = (kind: ParsedTicker['kind'], whenText: string, name: string) => {
    const end = endDate(whenText, issueDate), date = shortWhen(whenText);
    if (!end || !date || !name || end < today) return;
    items.push({ kind, date, name, end });
  };

  // Opportunities: the deadline chip on the big cards, the first line of details on the small ones.
  const opps = section(html, 'opps');
  for (const { body } of blocks(opps, 'a', 'opp')) {
    const when = text(first(/class="deadline">([\s\S]*?)<\/span>/, body)) || text(first(/class="meta">([\s\S]*?)<\/div>/, body)).split(' · ')[0];
    add('הזדמנות', when, text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, body)));
  }
  for (const { body } of blocks(opps, 'a', 'oppx')) {
    const details = first(/<br\s*\/?>\s*<span>([\s\S]*)<\/span>\s*<\/div>/, body) || '';
    add('הזדמנות', text(details).split(' · ')[0], text(first(/<b>([\s\S]*?)<\/b>/, body)));
  }

  // Events: the Israeli Space Forum's own events, then the world calendar.
  for (const { body } of blocks(section(html, 'forum'), 'a', 'fe')) {
    const place = text(first(/class="place">([\s\S]*?)<\/div>/, body)).replace(/^📍\s*/, '');
    const name = [text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, body)), place].filter(Boolean).join(' · ');
    add('אירוע', text(first(/class="fe-date">([\s\S]*?)<\/div>/, body)), name);
  }
  for (const { body } of blocks(section(html, 'events'), 'a', 'ev')) {
    const p = first(/<p>([\s\S]*?)<\/p>/, body) || '';
    const parts = text(p).split(' · ');
    const place = parts[1] && parts[1].length <= 40 ? parts[1] : '';            // a long second part is a description, not a place
    const name = [text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, body)), place].filter(Boolean).join(' · ');
    add('אירוע', parts[0] || '', name);
  }

  const seen = new Set<string>();
  return items
    .filter(t => !seen.has(t.name) && (seen.add(t.name), true))
    .sort((a, b) => a.end.localeCompare(b.end))
    .slice(0, MAX_TICKER);
}

/**
 * Parses an issue page. `today` (YYYY-MM-DD) drops ticker items that have already passed.
 * Throws when the page does not look like an issue, so a site redesign fails loudly instead of
 * blanking the wall.
 */
export function parseIssue(html: string, today: string): ParsedIssue {
  const canonical = decode(first(/<link rel="canonical" href="([^"]+)"/, html) || '');
  const issue_date = first(/\/(\d{4}-\d{2}-\d{2})\/?$/, canonical);
  if (!issue_date) throw new Error('הניוזלטר: לא נמצא תאריך גיליון בדף (canonical)');

  const rangeText = text(first(/<div class="range">([\s\S]*?)<\/div>/, html))
    || (decode(first(/<meta property="og:title" content="([^"]*)"/, html) || '').split('·')[1] || '').trim();
  const { news, images } = parseNews(html);
  if (!news.length) throw new Error(`הניוזלטר: לא נמצאו ידיעות בגיליון ${issue_date}`);

  // Featured on the wall: the lead story, then Israeli items, then the rest in page order; six in all.
  const order = [0, ...news.map((n, i) => (n.il ? i : -1)).filter(i => i > 0), ...news.map((_, i) => i)];
  const featured = [...new Set(order)].slice(0, Math.min(6, news.length));

  return {
    issue_date,
    source_url: canonical,
    content: {
      issue: { range: compactRange(rangeText) || issue_date, url: canonical },
      summary: featured.slice(0, 5).map(i => news[i].title),
      featured,
      news,
      ticker: parseTicker(html, issue_date, today),
    },
    images,
    forum: parseForum(html, issue_date, today),
  };
}

/**
 * The Forum's events: "יום שלישי · 13.10 · 09:30–15:00" or "רביעי-חמישי · 21–22.10". Events that ended before
 * `today` are left out, and so is anything whose date cannot be read.
 */
export function parseForum(html: string, issueDate: string, today: string): ForumEvent[] {
  const out: ForumEvent[] = [];
  for (const { open, body } of blocks(section(html, 'forum'), 'a', 'fe')) {
    const title = text(first(/<h3[^>]*>([\s\S]*?)<\/h3>/, body));
    const when = text(first(/class="fe-date">([\s\S]*?)<\/div>/, body));
    const d = /(\d{1,2})(?:\s*[–-]\s*(\d{1,2}))?\.(\d{1,2})(?:\.(\d{4}))?/.exec(when);
    if (!title || !d) continue;
    const end = endDate(`${d[2] || d[1]}.${d[3]}${d[4] ? '.' + d[4] : ''}`, issueDate);
    const start = endDate(`${d[1]}.${d[3]}${d[4] ? '.' + d[4] : ''}`, issueDate);
    if (!start || !end || end < today) continue;
    const t = /(\d{1,2}:\d{2})(?:\s*[–-]\s*(\d{1,2}:\d{2}))?/.exec(when);
    const pad = (x: string) => x.padStart(5, '0');
    const href = attr(open, 'href');
    out.push({
      title,
      place: text(first(/class="place">([\s\S]*?)<\/div>/, body)).replace(/^📍\s*/, ''),
      description: text(first(/<p>([\s\S]*?)<\/p>/, body)),
      url: /^https?:\/\//.test(href) ? href : '',
      start, end,
      ...(t ? { startTime: pad(t[1]), ...(t[2] ? { endTime: pad(t[2]) } : {}) } : {}),
    });
  }
  return out;
}

/** The newest issue date listed on the site's archive page, or null. */
export function latestFromArchive(html: string): string | null {
  const dates = [...html.matchAll(/href="\.\.\/(\d{4}-\d{2}-\d{2})\/"/g)].map(m => m[1]).sort();
  return dates.length ? dates[dates.length - 1] : null;
}
