// Space Wall — display runtime. Reads data/feed.json (regenerated by the backend), renders the wall,
// keeps clocks / countdowns / "updated ago" live, and re-renders when the feed changes.

const STAGE_W = 1920, STAGE_H = 1080;

// ---- config (URL query overrides) --------------------------------------------------------------
const q = new URLSearchParams(location.search);
const num = (k, d) => { const v = Number(q.get(k)); return Number.isFinite(v) && q.has(k) ? v : d; };
const bool = (k, d) => q.has(k) ? !/^(0|false|no|off)$/i.test(q.get(k)) : d;
const cfg = {
  feed: q.get('feed') || './data/feed.json',
  refresh: Math.max(10, num('refresh', 60)),      // seconds between feed polls
  loopSeconds: Math.min(15, Math.max(3, num('loop', 7))), // seconds per headline in the 24h loop
  globeSpeed: Math.min(180, Math.max(15, num('globe', 60))), // seconds per Earth rotation
  showQr: bool('qr', true),
  showDirectorate: bool('directorate', true),
  staleAfterMin: num('stale', 180),               // "live" dot turns amber when the feed is older than this
};

// ---- taxonomy ----------------------------------------------------------------------------------
const CATEGORIES = {
  defense:     { label: 'ביטחון',        color: '#9cc4e4' },
  geopolitics: { label: 'גאופוליטיקה',   color: '#c9b3e6' },
  launches:    { label: 'שיגורים',       color: '#8fd3c4' },
  industry:    { label: 'תעשייה',        color: '#8fd3c4' },
  israel:      { label: 'ישראל',         color: '#f0c7a0' },
  policy:      { label: 'מדיניות',       color: '#b9c7e0' },
  tech:        { label: 'טכנולוגיה',     color: '#9cc4e4' },
  ssa:         { label: 'SSA',           color: '#e9b872' },
  exploration: { label: 'חקר החלל',      color: '#c9b3e6' },
  weather:     { label: 'מזג אוויר חללי', color: '#e9b872' },
};
const ACTOR_COLORS = { us: '#dfe7f5', ru: '#c9b3e6', cn: '#e9b872', il: '#f0c7a0', eu: '#8fd3c4', other: '#9cc4e4' };
const tagOf = it => {
  const c = CATEGORIES[it.category] || {};
  return { label: it.tag || c.label || it.category || '', color: it.tagColor || c.color || '#9cc4e4' };
};

// ---- dom helpers -------------------------------------------------------------------------------
const $ = id => document.getElementById(id);
const el = (tag, cls, text) => { const e = document.createElement(tag); if (cls) e.className = cls; if (text != null) e.textContent = text; return e; };
const tagEl = it => { const t = tagOf(it); const s = el('span', 'tag', t.label); s.style.setProperty('--tag', t.color); return s; };

// ---- stage: scale to fit + stars ---------------------------------------------------------------
const stage = $('stage');
function fit() {
  stage.style.setProperty('--scale', Math.min(innerWidth / STAGE_W, innerHeight / STAGE_H));
}
addEventListener('resize', fit); fit();

(function stars() {
  const frag = document.createDocumentFragment();
  for (let i = 0; i < 90; i++) {
    const s = el('span'); const size = i % 7 === 0 ? 2.5 : 1.5;
    s.style.cssText = `left:${(i * 137.5) % 100}%;top:${(i * 71.3) % 100}%;width:${size}px;height:${size}px;animation:twinkle ${4 + (i % 5)}s ease-in-out ${(i % 9) * .7}s infinite`;
    frag.appendChild(s);
  }
  $('stars').appendChild(frag);
})();

$('spaceEmblem').setAttribute('speed', String(cfg.globeSpeed));

// ---- clocks ------------------------------------------------------------------------------------
const fmtIL = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Jerusalem', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
const fmtUTC = new Intl.DateTimeFormat('en-GB', { timeZone: 'UTC', hour: '2-digit', minute: '2-digit', hour12: false });
const fmtDate = new Intl.DateTimeFormat('he-IL', { timeZone: 'Asia/Jerusalem', weekday: 'long', day: 'numeric', month: 'long' });

let launchTargets = []; // [{ el, t }]
function tick() {
  const now = new Date();
  $('clockIL').textContent = fmtIL.format(now);
  $('clockUTC').textContent = fmtUTC.format(now);
  $('dateHe').textContent = fmtDate.format(now);
  for (const { el: e, t } of launchTargets) e.textContent = fmtT(t, now.getTime());
}
function fmtT(target, now) {
  const d = Math.max(0, target - now);
  const days = Math.floor(d / 864e5), h = Math.floor(d / 36e5) % 24, m = Math.floor(d / 6e4) % 60, s = Math.floor(d / 1e3) % 60;
  const p = n => String(n).padStart(2, '0');
  return `T-${days}d ${p(h)}:${p(m)}:${p(s)}`;
}
setInterval(tick, 1000); tick();

// ---- "updated X ago" ---------------------------------------------------------------------------
let generatedAt = null;
function updatedAgo() {
  const out = $('updatedAgo'), dot = $('liveDot');
  if (!generatedAt) { out.textContent = '—'; dot.classList.add('stale'); return; }
  const min = Math.max(0, Math.round((Date.now() - generatedAt) / 6e4));
  out.textContent = min < 1 ? 'עכשיו' : min < 60 ? `לפני ${min} דק׳` : min < 1440 ? `לפני ${Math.floor(min / 60)} שע׳` : `לפני ${Math.floor(min / 1440)} ימים`;
  dot.classList.toggle('stale', min > cfg.staleAfterMin);
}
setInterval(updatedAgo, 15000);

// ---- QR ----------------------------------------------------------------------------------------
function qrCanvas(url) {
  const canvas = el('canvas');
  try {
    if (typeof qrcode !== 'function') throw new Error('qrcode lib missing');
    if (qrcode.stringToBytesFuncs && qrcode.stringToBytesFuncs['UTF-8']) qrcode.stringToBytes = qrcode.stringToBytesFuncs['UTF-8'];
    const qr = qrcode(0, 'M'); qr.addData(url); qr.make();
    const n = qr.getModuleCount(), size = 112, cell = size / n;
    canvas.width = size; canvas.height = size;
    const c = canvas.getContext('2d');
    c.fillStyle = '#0b1430'; c.fillRect(0, 0, size, size);
    c.fillStyle = '#dfe7f5';
    for (let r = 0; r < n; r++) for (let col = 0; col < n; col++) if (qr.isDark(r, col)) {
      const x = Math.round(col * cell), y = Math.round(r * cell);
      c.fillRect(x, y, Math.round((col + 1) * cell) - x, Math.round((r + 1) * cell) - y);
    }
  } catch (e) { console.warn('QR failed', e); return null; }
  return canvas;
}

// ---- renderers ---------------------------------------------------------------------------------
function renderPush(items) {
  const loop = $('pushLoop'), track = $('pushTrack');
  track.innerHTML = '';
  $('pushCount').textContent = String(items.length);
  const row = it => {
    const r = el('div', 'push-item');
    const meta = el('div', 'push-meta');
    const src = el('div', 'push-meta-src'); src.append(tagEl(it), el('span', null, it.source || ''));
    meta.append(src, el('span', null, it.time || ''));
    r.append(meta, el('div', 'push-title', it.title || ''));
    if (it.titleEn) { const en = el('div', 'push-en', it.titleEn); en.dir = 'ltr'; r.append(en); }
    return r;
  };
  if (!items.length) { track.classList.add('static'); return; }
  // Measure one pass, then repeat the list until it fills the viewport, then duplicate for a seamless loop.
  items.forEach(it => track.append(row(it)));
  const reps = Math.max(1, Math.ceil(loop.clientHeight / Math.max(1, track.scrollHeight)));
  for (let i = 1; i < reps * 2; i++) items.forEach(it => track.append(row(it)));
  track.classList.remove('static');
  track.style.setProperty('--push-dur', `${items.length * reps * cfg.loopSeconds}s`);
  track.style.animation = 'none'; void track.offsetHeight; track.style.animation = '';
}

function renderDirectorate(items) {
  const box = $('directorate'), list = $('directorateList');
  list.innerHTML = '';
  const show = cfg.showDirectorate && items.length > 0;
  box.hidden = !show;
  if (!show) return;
  items.slice(0, 5).forEach(d => {
    const r = el('div', 'directorate-row');
    r.append(el('span', 'directorate-date', d.date || ''), el('span', null, d.name || ''));
    list.append(r);
  });
}

function renderNumbers(items) {
  const box = $('numbers'); box.innerHTML = '';
  items.slice(0, 4).forEach(n => {
    const c = el('div', 'number');
    c.append(el('span', 'number-value', n.value ?? ''), el('span', 'number-label', n.label ?? ''));
    box.append(c);
  });
}

function renderWeekly(items) {
  const box = $('weekly'); box.innerHTML = '';
  items.slice(0, 2).forEach(w => {
    const card = el('article', 'card');
    const media = el('div', 'card-media');
    if (w.image) { const img = el('img'); img.src = w.image; img.alt = ''; img.loading = 'eager'; media.append(img); }
    else media.append(el('div', 'card-media-note', w.imageNote || ''));
    media.append(el('div', 'card-fade'));
    if (w.credit) {
      const cr = el(w.creditHref ? 'a' : 'span', 'card-credit', w.credit); cr.dir = 'ltr';
      if (w.creditHref) cr.href = w.creditHref;
      media.append(cr);
    }
    const body = el('div', 'card-body');
    const meta = el('div', 'card-meta');
    const src = el('div', 'card-meta-src'); src.append(tagEl(w), el('span', null, w.source || ''));
    meta.append(src);
    if (cfg.showQr && w.url) {
      const qr = qrCanvas(w.url);
      if (qr) { const qb = el('div', 'card-qr'); qb.append(el('span', 'card-qr-label', 'לכתבה המלאה'), qr); meta.append(qb); }
    }
    body.append(meta, el('h3', 'card-title', w.title || ''));
    if (w.titleEn) { const en = el('div', 'card-en', w.titleEn); en.dir = 'ltr'; body.append(en); }
    if (w.why) { const why = el('div', 'card-why'); why.append(el('span', 'card-why-label', 'למה חשוב למנהלת'), el('span', 'card-why-text', w.why)); body.append(why); }
    card.append(media, body);
    box.append(card);
  });
}

function renderEvents(items) {
  const track = $('eventsTrack'); track.innerHTML = '';
  if (!items.length) return;
  const item = e => {
    const d = el('div', 'event');
    d.append(el('span', 'event-date', e.date || ''), el('span', null, e.name || ''), el('span', 'event-place', e.place || ''), el('span', 'event-sep', '◆'));
    return d;
  };
  items.forEach(e => track.append(item(e)));
  const reps = Math.max(1, Math.ceil(track.parentElement.clientWidth / Math.max(1, track.scrollWidth)));
  for (let i = 1; i < reps * 2; i++) items.forEach(e => track.append(item(e)));
  track.style.setProperty('--events-dur', `${items.length * reps * 9}s`);
  track.style.animation = 'none'; void track.offsetWidth; track.style.animation = '';
}

function renderLaunches(items) {
  const box = $('launches'); box.innerHTML = ''; launchTargets = [];
  items.slice(0, 4).forEach(l => {
    const c = el('div', 'launch');
    const info = el('div', 'launch-info');
    const name = el('span', 'launch-name', l.name || ''); name.dir = 'ltr';
    info.append(name, el('span', 'launch-site', l.site || ''));
    const t = el('span', 'launch-t', ''); t.dir = 'ltr';
    t.style.setProperty('--launch', l.color || ACTOR_COLORS[l.actor] || ACTOR_COLORS.other);
    c.append(info, t); box.append(c);
    const target = Date.parse(l.net);
    if (Number.isFinite(target)) launchTargets.push({ el: t, t: target }); else t.textContent = l.tminus || 'TBD';
  });
  tick();
}

function render(feed) {
  generatedAt = Date.parse(feed.generatedAt) || null;
  updatedAgo();
  $('weekRange').textContent = feed.weekRange || '';
  if (feed.orbital) { $('ssaLine1').textContent = feed.orbital.line1 || ''; $('ssaLine2').textContent = feed.orbital.line2 || ''; }
  if (feed.spaceWeather) { $('wxLine1').textContent = feed.spaceWeather.line1 || ''; $('wxLine2').textContent = feed.spaceWeather.line2 || ''; }
  renderPush(feed.push || []);
  renderDirectorate(feed.directorate || []);
  renderNumbers(feed.numbers || []);
  renderWeekly(feed.weekly || []);
  renderEvents(feed.events || []);
  renderLaunches(feed.launches || []);
}

// ---- feed polling ------------------------------------------------------------------------------
let lastBody = null;
async function loadFeed() {
  try {
    const res = await fetch(cfg.feed + (cfg.feed.includes('?') ? '&' : '?') + 't=' + Date.now(), { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const body = await res.text();
    if (body === lastBody) return;
    const feed = JSON.parse(body);
    lastBody = body;
    render(feed);
  } catch (e) {
    console.warn('feed load failed', e);
    updatedAgo();
  }
}
loadFeed();
setInterval(loadFeed, cfg.refresh * 1000);
